version: "3.8"
services:
  nginx-react-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: nginx-react
    env_file:
      - ./client/.env.local
    depends_on:
      - backend
    ports:
      - 5173:80

  backend:
    build:
      context: ./server
    container_name: node-server
    env_file:
      - ./server/config.env
    ports:
      - 8080:8080
