version: "3.8"
services:
  client:
    container_name: react-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    env_file:
      - ./client/.env.local
    restart: on-failure
    ports:
      - "5173:5173"

  backend:
    container_name: node-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - ./server/config.env
    restart: on-failure
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: nginx
    restart: always
    depends_on:
      - client
      - backend
