# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy client

on:
  push:
    branches:
      - 'master'
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ['self-hosted', 'client']
    defaults:
      run:
        working-directory: ./client/

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: client
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'
      - run: npm ci
      - run: npm run build
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
